apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium  # AKS default managed disk
  resources:
    requests:
      storage: 5Gi
